### PR TITLE
Redesign and CNAME

### PR DESCRIPTION
**Pull request by stewart**
Updates design to match new [Artoo](http://artoo.io) design. Also adds CNAME file so that `gitnesse.com` will be used as the domain instead of redirecting to `hybridgroup.github.io/gitnesse`.

New look:
New Appearance

### CODE REVIEW

**Comment by deadprogram** [comment]
That looks amazing!!!

**Comment by stewart** [comment]
Want to add some mobile/tablet CSS before this gets merged.

**Comment by stewart** [comment]
:shipit:

**Comment by deadprogram** [comment]
:rocket:

**Pull request merged**
