### PR TITLE
Feature/preserve first line tags

### PR DESCRIPTION
**Pull request by ess**
This was done up specifically to address hybridgroup/gitnesse#16 , but also basically tries to guarantee that what's in a gherkin block is what gets written to file.

For the sake of readability for the test, I also broke the multiline text out into data files.

### CODE REVIEW

**Comment by deadprogram** [comment]
This looks cool, @stewart check it out!

**Comment by ess** [comment]
Unintended positive side-effect: While there is not a test for it, it appears that this change may also fix #14

**Comment by stewart** [comment]
Awesome! I'm currently making (slow) progress on a re-write for Gitnesse, and I'll make sure this gets rolled into it (credited to you, of course).

**Comment by ess** [comment]
I noticed the rewrite branch, but figured this might still have a place in the code until that can be finalized. That and I didn't really have time to make heads or tails of the rewrite ;)

Good luck!

**Comment by stewart** [comment]
Support for first-line cucumber tags is now in the latest release of Gitnesse. Have added you to the `CONTRIBUTORS.md` file. Thanks again!

**Pull request closed without merging**
