### PR TITLE
Add rvmrc

### PR DESCRIPTION
**Pull request by cored**

### CODE REVIEW

**Comment by stewart** [comment]
Possibly also a .rbenv-version?

**Comment by cored** [comment]
I think, yes that can be done. Normally we use rvm for most of the projects, but I guess a rbenv can be added too.

**Comment by deadprogram** [comment]
Please do not. The reason is that RVM reads rbenv flles too... which is not
really what we want. I suggest either only add .rvmrc, or do not add either
one.

On Tue, Nov 13, 2012 at 5:40 PM, Rafael George notifications@github.comwrote:

> I think, yes that can be done. Normally we use rvm for most of the
> projects, but I guess a rbenv can be added too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hybridgroup/gitnesse/pull/5#issuecomment-10351945.

## 

Ron Evans
The Hybrid Group
http://hybridgroup.com
p. 310-916-9924
m. 310-597-1013

**Comment by MarioRicalde** [comment]
I would say stay away on adding .rvmrc file. I think that's something the end user should have control on.

**Comment by phlipper** [comment]
You can use a `.ruby-version` file as described [here](https://gist.github.com/1912050). Both RVM and rbenv support usage of that file. The format is::

```
1.9.2@gitnesse
```

**Comment by deadprogram** [comment]
Anyone going to incorporate @phlipper feedback?

**Comment by stewart** [comment]
Is it alright if I close this? I don't think it's really necessary to specify a ruby version or gemset for Gitnesse.

**Comment by deadprogram** [comment]
Agreed. Let the people use the version of Ruby that they want... and can
get working ;)

On Tue, Dec 18, 2012 at 12:00 PM, Andrew Stewart
notifications@github.comwrote:

> Is it alright if I close this? I don't think it's really necessary to
> specify a ruby version or gemset for Gitnesse.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hybridgroup/gitnesse/pull/5#issuecomment-11502528.

## 

Ron Evans
The Hybrid Group
http://hybridgroup.com
p. 310-916-9924
m. 310-597-1013

**Pull request closed without merging**
